$schema: https://azuremlschemas.azureedge.net/latest/pipelineComponent.schema.json
type: pipeline
name: detectnet_v2_data_pipeline
version: 1
display_name: pipeline component with detectnet_v2 workflow
description: pipeline component with detectnet_v2 workflow
inputs:
  num_gpus:
    type: integer
  key:
    type: string
  compute_train_node:
    type: string
  original_specs:
    type: uri_folder
  config_files_dir: 
    type: uri_folder
outputs:
  data_dir:
    type: uri_folder
  tf_records_dir:
    type: uri_folder
  base_model_dir:
    type: uri_folder
  unpruned_model_dir:
    type: uri_folder
  pruned_model_dir:
    type: uri_folder
  pruned_and_retrained_model_dir:
    type: uri_folder
  trained_model_dir:
    type: uri_folder
  pruned_and_retrained_model_inference_dir:
    type: uri_folder
  pruned_and_retrained_exported_model_dir:
    type: uri_folder
  calibration_tensorfile_dir:
    type: uri_folder
  int8_model_dir:
    type: uri_folder
  pruned_and_retrained_trt_model_dir:
    type: uri_folder
  int8_model_inference_dir:
    type: uri_folder
  qat_trained_model_dir:
    type: uri_folder
  qat_trt_model_dir:
    type: uri_folder
  qat_int8_model_inference_dir:
    type: uri_folder
  triton_model_repository_dir:
    type: uri_folder
jobs: 
  download_data:
    type: command
    component: azureml:download_images_and_labels:1
    compute: ${{parent.inputs.compute_train_node}}
    inputs:
      url_images: "https://s3.eu-central-1.amazonaws.com/avg-kitti/data_object_image_2.zip"
      url_labels: "https://s3.eu-central-1.amazonaws.com/avg-kitti/data_object_label_2.zip"
      images_checksum: '^351c5a2aa0cd9238b50174a3a62b846bc5855da256b82a196431d60ff8d43617$'
      labels_checksum: '^4efc76220d867e1c31bb980bbf8cbc02599f02a9cb4350effa98dbb04aaed880$' 
    outputs:
      data_dir: ${{parent.outputs.data_dir}}
  dataset_convert:
    type: command
    component: azureml:tao_detectnet_v2_dataset_convert:1
    compute: ${{parent.inputs.compute_train_node}}
    inputs:
      specs_dir: ${{parent.inputs.original_specs}}
      data_dir: ${{parent.jobs.download_data.outputs.data_dir}}
      dataset_export_spec: detectnet_v2_tfrecords_kitti_trainval.txt
      output_filename: kitti_trainval/kitti_trainval
    outputs:
      tf_records_dir: ${{parent.outputs.tf_records_dir}}
  download_model:
    type: command
    component: azureml:tao_detectnet_v2_download_model:1
    compute: ${{parent.inputs.compute_train_node}}
    inputs:
      model_name: pretrained_detectnet_v2:resnet18
      model_subdir: pretrained_resnet18
    outputs:
      base_model_dir: ${{parent.outputs.base_model_dir}}
  tao_train_base:
    type: command
    component: azureml:tao_detectnet_v2_train:1
    compute: ${{parent.inputs.compute_train_node}}
    inputs:
      data_dir: ${{parent.jobs.download_data.outputs.data_dir}}
      base_model_dir: ${{parent.jobs.download_model.outputs.base_model_dir}}
      tf_records_dir: ${{parent.jobs.dataset_convert.outputs.tf_records_dir}}
      original_specs: ${{parent.inputs.original_specs}}
      num_gpus: ${{parent.inputs.num_gpus}}
      key: ${{parent.inputs.key}}
      name_string_for_the_model: 'resnet18_detector'
      model_subfolder: experiment_dir_unpruned
      specs_file: detectnet_v2_train_resnet18_kitti.txt
    outputs:
      trained_model_dir: ${{parent.outputs.unpruned_model_dir}}
  tao_evaluate_unpruned:
    type: command
    component: azureml:tao_detectnet_v2_evaluate:1
    compute: ${{parent.inputs.compute_train_node}}
    inputs:
      data_dir: ${{parent.jobs.download_data.outputs.data_dir}}
      base_model_dir: ${{parent.jobs.download_model.outputs.base_model_dir}}
      tf_records_dir: ${{parent.jobs.dataset_convert.outputs.tf_records_dir}}
      original_specs: ${{parent.inputs.original_specs}}
      key: ${{parent.inputs.key}}
      model_name: resnet18_detector.tlt
      model_subfolder: experiment_dir_unpruned/weights
      target_model_dir: ${{parent.jobs.tao_train_base.outputs.trained_model_dir}}
      specs_file: detectnet_v2_train_resnet18_kitti.txt
  tao_prune:
    type: command
    component: azureml:tao_detectnet_v2_prune:1
    compute: ${{parent.inputs.compute_train_node}}
    inputs: 
      unpruned_model_dir: ${{parent.jobs.tao_train_base.outputs.trained_model_dir}}
      unprunned_model_subfolder: experiment_dir_unpruned
      unprunned_model_name: resnet18_detector
      prunned_model_subfolder: experiment_dir_pruned
      prunned_model_name: resnet18_nopool_bn_detectnet_v2_pruned
      equalization_criterion: union
      pth: "0.0000052"
      key: ${{parent.inputs.key}}
    outputs:
      pruned_model_dir: ${{parent.outputs.pruned_model_dir}}
  tao_train_pruned:
    type: command
    component: azureml:tao_detectnet_v2_train:1
    compute: ${{parent.inputs.compute_train_node}}
    inputs:
      data_dir: ${{parent.jobs.download_data.outputs.data_dir}}
      base_model_dir: ${{parent.jobs.tao_prune.outputs.pruned_model_dir}}
      tf_records_dir: ${{parent.jobs.dataset_convert.outputs.tf_records_dir}}
      original_specs: ${{parent.inputs.original_specs}}
      num_gpus: ${{parent.inputs.num_gpus}}
      key: ${{parent.inputs.key}}
      name_string_for_the_model: resnet18_detector_pruned
      model_subfolder: experiment_dir_retrain
      specs_file: detectnet_v2_retrain_resnet18_kitti.txt
    outputs:
      trained_model_dir: ${{parent.outputs.pruned_and_retrained_model_dir}}
  tao_evaluate_pruned:
    type: command
    component: azureml:tao_detectnet_v2_evaluate:1
    compute: ${{parent.inputs.compute_train_node}}
    inputs:
      data_dir: ${{parent.jobs.download_data.outputs.data_dir}}
      base_model_dir: ${{parent.jobs.tao_prune.outputs.pruned_model_dir}}
      tf_records_dir: ${{parent.jobs.dataset_convert.outputs.tf_records_dir}}
      original_specs: ${{parent.inputs.original_specs}}
      key: ${{parent.inputs.key}}
      model_name: resnet18_detector_pruned.tlt
      model_subfolder: experiment_dir_retrain/weights
      target_model_dir: ${{parent.jobs.tao_train_pruned.outputs.trained_model_dir}}
      specs_file: detectnet_v2_retrain_resnet18_kitti.txt
  tao_inference_pruned_and_trained:
    type: command
    component: azureml:tao_detectnet_v2_inference:1
    compute: ${{parent.inputs.compute_train_node}}
    inputs:
      data_dir: ${{parent.jobs.download_data.outputs.data_dir}}
      input_subfolder: /testing/image_2 
      model_dir: ${{parent.jobs.tao_train_pruned.outputs.trained_model_dir}}
      original_specs: ${{parent.inputs.original_specs}}
      specs_file: detectnet_v2_inference_kitti_tlt.txt 
      key: ${{parent.inputs.key}}
      output_subfolder: tlt_infer_testing
    outputs:
      results_dir: ${{parent.outputs.pruned_and_retrained_model_inference_dir}}
  tao_export_pruned_and_trained:
    type: command
    component: azureml:tao_detectnet_v2_export:1
    compute: ${{parent.inputs.compute_train_node}}
    inputs:
      source_model_dir: ${{parent.jobs.tao_train_pruned.outputs.trained_model_dir}}
      source_subfolder: experiment_dir_retrain
      source_model_name: resnet18_detector_pruned
      exported_subfolder: experiment_dir_final
      exported_model_name: resnet18_detector
      cal_image_dir: ${{parent.jobs.download_data.outputs.data_dir}}
      cal_data_dir: ${{parent.jobs.download_data.outputs.data_dir}}
      experiment_specs_dir: ${{parent.inputs.original_specs}}
      key: ${{parent.inputs.key}}
    outputs:
      exported_model_dir: ${{parent.outputs.pruned_and_retrained_exported_model_dir}}
  tao_calibration_tensorfile:
    type: command
    component: azureml:tao_detectnet_v2_calibration_tensorfile:1
    compute: ${{parent.inputs.compute_train_node}}
    inputs:
      data_dir: ${{parent.jobs.download_data.outputs.data_dir}}
      base_model_dir: ${{parent.jobs.tao_prune.outputs.pruned_model_dir}}
      tf_records_dir: ${{parent.jobs.dataset_convert.outputs.tf_records_dir}}
      original_specs: ${{parent.inputs.original_specs}}
      specs_file: detectnet_v2_retrain_resnet18_kitti.txt
      output_subfolder: experiment_dir_final
      output_filename: calibration.tensor
      max_batches: 10
    outputs:
      output_dir: ${{parent.outputs.calibration_tensorfile_dir}} 
  tao_export_to_int8:
    type: command
    component: azureml:tao_detectnet_v2_export:1
    compute: ${{parent.inputs.compute_train_node}}
    inputs:
      source_model_dir: ${{parent.jobs.tao_train_pruned.outputs.trained_model_dir}}
      source_subfolder: experiment_dir_retrain
      source_model_name: resnet18_detector_pruned
      exported_subfolder: experiment_dir_final
      exported_model_name: resnet18_detector
      key: ${{parent.inputs.key}}
      cal_image_dir: ${{parent.jobs.download_data.outputs.data_dir}}
      cal_data_dir: ${{parent.jobs.tao_calibration_tensorfile.outputs.output_dir}}
      cal_data_filename: calibration.tensor
      experiment_specs_dir: ${{parent.inputs.original_specs}}
      cal_cache_filename: calibration.bin
      engine_filename: resnet18_detector.trt.int8
      data_type: int8
      batches: 10
      batch_size: 4 
      max_batch_size: 4 
      verbose: active
    outputs:
      exported_model_dir: ${{parent.outputs.int8_model_dir}}
  tao_convert_int8:
    type: command
    component: azureml:tao_convert:1
    compute: ${{parent.inputs.compute_train_node}}
    inputs:
      model_type: detectnet_v2
      etlt_model_dir: ${{parent.jobs.tao_export_pruned_and_trained.outputs.exported_model_dir}}
      etlt_model_name: resnet18_detector.etlt
      etlt_model_subfolder: experiment_dir_final
      trt_model_name: resnet18_detector.trt
      trt_model_subfolder: experiment_dir_final
      cal_cache_dir: ${{parent.jobs.tao_export_to_int8.outputs.exported_model_dir}}
      key: ${{parent.inputs.key}}
      input_dimensions: 3,384,1248
      output_nodes: output_cov/Sigmoid,output_bbox/BiasAdd
      cal_cache_filename: calibration.bin
      input_dimension_ordering: nchw
      max_batch_size: 64
      engine_datatype: int8
      cal_batch_size: 4
    outputs:
      trt_model_dir: ${{parent.outputs.pruned_and_retrained_trt_model_dir}}
  tao_inference_int8:
    type: command
    component: azureml:tao_detectnet_v2_inference:1
    compute: ${{parent.inputs.compute_train_node}}
    inputs:
      data_dir: ${{parent.jobs.download_data.outputs.data_dir}}
      input_subfolder: /testing/image_2 
      model_dir: ${{parent.jobs.tao_convert_int8.outputs.trt_model_dir}}
      original_specs: ${{parent.inputs.original_specs}}
      specs_file: detectnet_v2_inference_kitti_etlt.txt
      key: ${{parent.inputs.key}}
      output_subfolder: etlt_infer_testing
    outputs:
      results_dir: ${{parent.outputs.int8_model_inference_dir}}
  tao_train_qat:
    type: command
    component: azureml:tao_detectnet_v2_train:1
    compute: ${{parent.inputs.compute_train_node}}
    inputs:
      data_dir: ${{parent.jobs.download_data.outputs.data_dir}}
      base_model_dir: ${{parent.jobs.tao_prune.outputs.pruned_model_dir}}
      tf_records_dir: ${{parent.jobs.dataset_convert.outputs.tf_records_dir}}
      original_specs: ${{parent.inputs.original_specs}}
      num_gpus: ${{parent.inputs.num_gpus}}
      key: ${{parent.inputs.key}}
      name_string_for_the_model: resnet18_detector_pruned_qat
      model_subfolder: experiment_dir_retrain_qat
      specs_file: detectnet_v2_retrain_resnet18_kitti_qat.txt
    outputs:
      trained_model_dir: ${{parent.outputs.qat_trained_model_dir}}
  tao_evaluate_qat:
    type: command
    component: azureml:tao_detectnet_v2_evaluate:1
    compute: ${{parent.inputs.compute_train_node}}
    inputs:
      data_dir: ${{parent.jobs.download_data.outputs.data_dir}}
      base_model_dir: ${{parent.jobs.tao_prune.outputs.pruned_model_dir}}
      tf_records_dir: ${{parent.jobs.dataset_convert.outputs.tf_records_dir}}
      original_specs: ${{parent.inputs.original_specs}}
      key: ${{parent.inputs.key}}
      model_name: resnet18_detector_pruned_qat.tlt
      model_subfolder: experiment_dir_retrain_qat/weights
      target_model_dir: ${{parent.jobs.tao_train_qat.outputs.trained_model_dir}}
      specs_file: detectnet_v2_retrain_resnet18_kitti_qat.txt
      running_framework: tlt
  tao_export_to_qat:
    type: command
    component: azureml:tao_detectnet_v2_export:1
    compute: ${{parent.inputs.compute_train_node}}
    inputs:
      source_model_dir: ${{parent.jobs.tao_train_qat.outputs.trained_model_dir}}
      source_subfolder: experiment_dir_retrain_qat
      source_model_name: resnet18_detector_pruned_qat
      exported_subfolder: experiment_dir_final
      exported_model_name: resnet18_detector_qat
      key: ${{parent.inputs.key}}
      cal_image_dir: ${{parent.jobs.download_data.outputs.data_dir}}
      cal_data_dir: ${{parent.jobs.tao_calibration_tensorfile.outputs.output_dir}}
      experiment_specs_dir: ${{parent.inputs.original_specs}}
      cal_cache_filename: calibration.qat.bin
      engine_filename: resnet18_detector_qat.trt.int8 
      data_type: int8
      batch_size: 64 
      max_batch_size: 64 
      verbose: active
    outputs:
      exported_model_dir: ${{parent.outputs.qat_trt_model_dir}}
  tao_evaluate_qat_int8:
    type: command
    component: azureml:tao_detectnet_v2_evaluate:1
    compute: ${{parent.inputs.compute_train_node}}
    inputs:
      data_dir: ${{parent.jobs.download_data.outputs.data_dir}}
      base_model_dir: ${{parent.jobs.tao_prune.outputs.pruned_model_dir}}
      tf_records_dir: ${{parent.jobs.dataset_convert.outputs.tf_records_dir}}
      original_specs: ${{parent.inputs.original_specs}}
      key: ${{parent.inputs.key}}
      model_name: resnet18_detector_qat.trt.int8
      model_subfolder: experiment_dir_final
      target_model_dir: ${{parent.jobs.tao_export_to_qat.outputs.exported_model_dir}}
      specs_file: detectnet_v2_retrain_resnet18_kitti_qat.txt
      running_framework: tensorrt
  tao_inference_qat_int8:
    type: command
    component: azureml:tao_detectnet_v2_inference:1
    compute: ${{parent.inputs.compute_train_node}}
    inputs:
      data_dir: ${{parent.jobs.download_data.outputs.data_dir}}
      input_subfolder: /testing/image_2 
      model_dir: ${{parent.jobs.tao_export_to_qat.outputs.exported_model_dir}}
      original_specs: ${{parent.inputs.original_specs}}
      specs_file: detectnet_v2_inference_kitti_etlt_qat.txt
      key: ${{parent.inputs.key}}
      output_subfolder: tlt_infer_testing_qat
    outputs:
      results_dir: ${{parent.outputs.qat_int8_model_inference_dir}}
  triton_create_model_repository:
    type: command
    component: azureml:triton_create_model_repository:1
    compute: ${{parent.inputs.compute_train_node}}
    inputs:
      source_model_dir: ${{parent.jobs.tao_convert_int8.outputs.trt_model_dir}}
      source_subfolder: experiment_dir_final
      source_model_name: resnet18_detector.trt
      config_files_dir: ${{parent.inputs.config_files_dir}}
      config_filename: config.pbtxt
      repository_model_name: detectnet_tao
      model_filename: model.plan
      new_config_filename: config.pbtxt
    outputs:
      triton_model_repository_dir: ${{parent.outputs.triton_model_repository_dir}}