set -x

# map the output data location to the directory name used by the script

export MODEL_TYPE=$1
export ETLT_MODEL_DIR=$2/${MODEL_TYPE}
export ETLT_MODEL_NAME=$3
export ETLT_MODEL_SUBFOLDER=$4
export TRT_MODEL_NAME=$5
export TRT_MODEL_SUBFOLDER=$6
export TRT_MODEL_DIR=$7/${MODEL_TYPE}
export KEY=$8
export INPUT_DIMENSIONS=$9
export OUTPUT_NODES=${10}
export CAL_CACHE_DIR=${11}/${MODEL_TYPE}
export CAL_CACHE_FILENAME=${12}
export CAL_BATCH_SIZE=${13}
export MAX_BATCH_SIZE=${14}
export ENGINE_DATATYPE=${15}
export MAX_WORKSPACE_SIZE=${16}
export INPUTS_DIMENSION_ORDERING=${17}
export OPTIMIZATION_PROFILES=${18}
export STRICT_TYPE_CONSTRAINTS=${19}
export DLA_CORE_INDEX=${20}

mkdir ${TRT_MODEL_DIR}
mkdir -p ${TRT_MODEL_DIR}/${TRT_MODEL_SUBFOLDER}

ADDITIONAL_ARGS=""

if [[ "${CAL_CACHE_FILENAME}" != "ND" ]]
then
    ADDITIONAL_ARGS="$ADDITIONAL_ARGS -c ${CAL_CACHE_DIR}/${ETLT_MODEL_SUBFOLDER}/${CAL_CACHE_FILENAME}"
    ls ${CAL_CACHE_DIR}/${ETLT_MODEL_SUBFOLDER}/${CAL_CACHE_FILENAME}
fi

if [[ "${INPUTS_DIMENSION_ORDERING}" != "ND" ]]
then
    ADDITIONAL_ARGS="$ADDITIONAL_ARGS -i ${INPUTS_DIMENSION_ORDERING}"
fi

if [[ "${MAX_BATCH_SIZE}" != "ND" ]]
then
    ADDITIONAL_ARGS="$ADDITIONAL_ARGS -m ${MAX_BATCH_SIZE}"
fi

if [[ "${ENGINE_DATATYPE}" != "ND" ]]
then
    ADDITIONAL_ARGS="$ADDITIONAL_ARGS -t ${ENGINE_DATATYPE}"
fi

if [[ "${CAL_BATCH_SIZE}" != "ND" ]]
then
    ADDITIONAL_ARGS="$ADDITIONAL_ARGS -b ${CAL_BATCH_SIZE}"
fi

if [[ "${MAX_WORKSPACE_SIZE}" != "ND" ]]
then
    ADDITIONAL_ARGS="$ADDITIONAL_ARGS -w ${MAX_WORKSPACE_SIZE}"
fi

if [[ "${OPTIMIZATION_PROFILES}" != "ND" ]]
then
    ADDITIONAL_ARGS="$ADDITIONAL_ARGS -p ${OPTIMIZATION_PROFILES}"
fi

if [[ "${STRICT_TYPE_CONSTRAINTS}" != "ND" ]]
then
    ADDITIONAL_ARGS="$ADDITIONAL_ARGS -s"
fi

if [[ "${DLA_CORE_INDEX}" != "ND" ]]
then
    ADDITIONAL_ARGS="$ADDITIONAL_ARGS -u ${DLA_CORE_INDEX}"
fi

ls ${ETLT_MODEL_DIR}/${ETLT_MODEL_SUBFOLDER}/${ETLT_MODEL_NAME}

converter ${ETLT_MODEL_DIR}/${ETLT_MODEL_SUBFOLDER}/${ETLT_MODEL_NAME} \
                   -k $KEY \
                   -d $INPUT_DIMENSIONS \
                   -o $OUTPUT_NODES \
                   -e ${TRT_MODEL_DIR}/${TRT_MODEL_SUBFOLDER}/${TRT_MODEL_NAME} \
                   $ADDITIONAL_ARGS

ls -lh ${TRT_MODEL_DIR}/${TRT_MODEL_SUBFOLDER}/

