$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline
experiment_name: NVIDIA_TAO_tfv3_22_05_tf1_15_4_DETECTNET_V2_pc
settings:
  default_compute: azureml:gpu-cluster-standard-nc6s-v3
inputs:
  num_gpus: 1
  key: 'tlt_encode'
  original_specs:
    type: uri_folder
    path: ./specs/
  config_files_dir: 
    type: uri_folder
    path: ./config_files/   
  compute_train_node: gpu-cluster-standard-nc6s-v3
outputs: 
  triton_model_repository_dir:
    type: uri_folder
jobs:
  detect_net_workflow:
    type: pipeline
    component: azureml:detectnet_v2_data_pipeline:1
    inputs:
      num_gpus: ${{parent.inputs.num_gpus}}
      key: ${{parent.inputs.key}}
      compute_train_node: ${{parent.inputs.compute_train_node}}
      original_specs: ${{parent.inputs.original_specs}}
      config_files_dir: ${{parent.inputs.config_files_dir}}
    outputs:
      triton_model_repository_dir: ${{parent.outputs.triton_model_repository_dir}}